version: "3.7"

services:
  ###> doctrine/doctrine-bundle ###
  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: app
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - "4000:80"
  app:
    build: .
    container_name: app-container
    restart: always
    volumes:
      - ./:/var/www
    ports:
      - "8080:80"
volumes:
  ###> doctrine/doctrine-bundle ###
  db-data:
  www:
###< doctrine/doctrine-bundle ###
