version: "3.7"

services:
  ###> doctrine/doctrine-bundle ###
  db:
    image: mysql
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: app
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - "4000:80"
  php7-2:
    image: php:7.2-apache
    container_name: php-container
    restart: always
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:80"
volumes:
  ###> doctrine/doctrine-bundle ###
  db-data:
  html:
###< doctrine/doctrine-bundle ###
